"""Add Instagram and YouTube fields to CreatorProfile

Revision ID: 22d48585032b
Revises: a8b57869c9d8
Create Date: 2026-02-22 20:20:38.437093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d48585032b'
down_revision: Union[str, Sequence[str], None] = 'a8b57869c9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
