"""Add created_at to users

Admins had no way to tell when a creator or brand registered — the users
table never had a timestamp column. Backfills existing rows to now() since
their real signup time was never recorded.

HAND-WRITTEN, not autogenerated, per the convention in d81f4a2c9b03.

Revision ID: a1c9e4f2b8d6
Revises: f7a2c4e91b35
Create Date: 2026-08-22
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a1c9e4f2b8d6"
down_revision: Union[str, Sequence[str], None] = "f7a2c4e91b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "users"
COLUMN = "created_at"


def upgrade() -> None:
    columns = [c["name"] for c in sa.inspect(op.get_bind()).get_columns(TABLE)]
    if COLUMN in columns:
        return

    op.add_column(
        TABLE,
        sa.Column(
            COLUMN, sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column(TABLE, COLUMN)
