"""add_instagram_and_youtube_columns_to_creator_profiles

Revision ID: a8b57869c9d8
Revises: fe798cbf3e4e
Create Date: 2026-02-22 18:53:21.635992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b57869c9d8'
down_revision: Union[str, Sequence[str], None] = 'fe798cbf3e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # instagram_creator_cache may not exist on a fresh DB — use IF EXISTS
    op.execute("DROP INDEX IF EXISTS ix_instagram_creator_cache_username")
    op.execute("DROP TABLE IF EXISTS instagram_creator_cache")
    op.add_column('creator_profiles', sa.Column('instagram_username', sa.String(), nullable=True))
    op.add_column('creator_profiles', sa.Column('instagram_profile_link', sa.String(), nullable=True))
    op.add_column('creator_profiles', sa.Column('youtube_username', sa.String(), nullable=True))
    op.add_column('creator_profiles', sa.Column('youtube_profile_link', sa.String(), nullable=True))
    op.create_index(op.f('ix_creator_profiles_instagram_username'), 'creator_profiles', ['instagram_username'], unique=False)
    op.create_index(op.f('ix_creator_profiles_youtube_username'), 'creator_profiles', ['youtube_username'], unique=False)
    op.drop_column('creator_profiles', 'profile_link')
    op.drop_column('creator_profiles', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('creator_profiles', sa.Column('profile_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_creator_profiles_youtube_username'), table_name='creator_profiles')
    op.drop_index(op.f('ix_creator_profiles_instagram_username'), table_name='creator_profiles')
    op.drop_column('creator_profiles', 'youtube_profile_link')
    op.drop_column('creator_profiles', 'youtube_username')
    op.drop_column('creator_profiles', 'instagram_profile_link')
    op.drop_column('creator_profiles', 'instagram_username')
    op.create_table('instagram_creator_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('instagram_creator_cache_pkey'))
    )
    op.create_index(op.f('ix_instagram_creator_cache_username'), 'instagram_creator_cache', ['username'], unique=True)
    # ### end Alembic commands ###
