"""add instagram analytics

Revision ID: ab0b60e6d270
Revises: eb8943fe94e8
Create Date: 2026-01-23 22:08:37.245651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0b60e6d270'
down_revision: Union[str, Sequence[str], None] = 'eb8943fe94e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram_username')
    # ### end Alembic commands ###
