"""Add scrape_jobs table

Records the outcome of each background scrape so failures stop being silent.

HAND-WRITTEN, NOT AUTOGENERATED.

`alembic revision --autogenerate` produced this table correctly but also emitted
a pile of unrelated and actively broken operations, which have been removed:

  * `op.drop_constraint(None, 'brand_profiles', type_='foreignkey')` — dropping
    a constraint by `None` raises on PostgreSQL. Autogenerate wanted to rename
    the existing unnamed FKs; there is no reason to touch them.
  * `alter_column(..., nullable=False)` on instagram_* and youtube_* — artifacts
    of comparing against a SQLite scratch database. Those columns are already
    NOT NULL in PostgreSQL, so the statements are pointless and would take
    unnecessary table locks.

This revision now does exactly one thing: create scrape_jobs.

Revision ID: bb841ad7d467
Revises: b7e4c1a90f22
Create Date: 2026-08-10
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bb841ad7d467"
down_revision: Union[str, Sequence[str], None] = "b7e4c1a90f22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE = "scrape_jobs"


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    if TABLE in inspector.get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"],
            name="scrape_jobs_user_id_fkey", ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="scrape_jobs_pkey"),
    )
    op.create_index("ix_scrape_jobs_user_id", TABLE, ["user_id"], unique=False)
    op.create_index(
        "ix_scrape_jobs_user_platform_started",
        TABLE,
        ["user_id", "platform", "started_at"],
        unique=False,
    )


def downgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    if TABLE not in inspector.get_table_names():
        return
    op.drop_index("ix_scrape_jobs_user_platform_started", table_name=TABLE)
    op.drop_index("ix_scrape_jobs_user_id", table_name=TABLE)
    op.drop_table(TABLE)
