"""Add opportunity_interests

Records a creator expressing interest in an anonymised brand opportunity — the
step that closes the marketplace loop.

HAND-WRITTEN, not autogenerated. Autogenerate has twice emitted destructive or
dialect-specific noise in this project (see dd173ce633c3 and bb841ad7d467), so
migrations here do exactly one thing and are checked by tests/test_schema_parity.py.

NOTE: `campaign_id` was added to this revision rather than in a follow-up. That
is only acceptable because this table has never existed outside throwaway local
test databases — it is unreleased and unapplied anywhere real. Amending an
already-applied migration is what caused the dd173ce633c3 incident; do not do it
once a revision has shipped.

Revision ID: c3f5a71b8e40
Revises: d81f4a2c9b03
Create Date: 2026-08-12
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c3f5a71b8e40"
down_revision: Union[str, Sequence[str], None] = "d81f4a2c9b03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "opportunity_interests"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("opportunity_snapshot", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        # CURRENT_TIMESTAMP, not now(): portable across PostgreSQL and SQLite.
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"],
            name="opportunity_interests_creator_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["users.id"],
            name="opportunity_interests_brand_id_fkey", ondelete="CASCADE",
        ),
        # SET NULL: closing or removing a campaign must not erase the record
        # that a creator applied.
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"],
            name="opportunity_interests_campaign_id_fkey", ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="opportunity_interests_pkey"),
        sa.UniqueConstraint(
            "creator_id", "opportunity_id", name="uq_interest_creator_opportunity"
        ),
    )
    op.create_index("ix_opportunity_interests_creator_id", TABLE, ["creator_id"])
    op.create_index("ix_opportunity_interests_brand_id", TABLE, ["brand_id"])
    op.create_index("ix_opportunity_interests_opportunity_id", TABLE, ["opportunity_id"])
    op.create_index("ix_opportunity_interests_campaign_id", TABLE, ["campaign_id"])
    op.create_index("ix_opportunity_interests_brand_created", TABLE, ["brand_id", "created_at"])


def downgrade() -> None:
    if TABLE not in sa.inspect(op.get_bind()).get_table_names():
        return
    for ix in (
        "ix_opportunity_interests_brand_created",
        "ix_opportunity_interests_campaign_id",
        "ix_opportunity_interests_opportunity_id",
        "ix_opportunity_interests_brand_id",
        "ix_opportunity_interests_creator_id",
    ):
        op.drop_index(ix, table_name=TABLE)
    op.drop_table(TABLE)
