"""add ai_summary column

Revision ID: cee76db5231d
Revises: 8230328dad8f
Create Date: 2026-03-27 01:16:13.811244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cee76db5231d'
down_revision: Union[str, Sequence[str], None] = '8230328dad8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Previously auto-generated incorrectly (was dropping columns).
    # Columns are already added by f9ca5e8aed1b — no-op.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('brand_deals_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('creator_profiles', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('creator_profiles', sa.Column('cached_brand_deals', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('creator_profiles', sa.Column('summary_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
