"""Add campaigns

Lets a brand state what it is actually offering — real fee, real deliverables,
real deadline — so the AI stops inventing commercial terms.

HAND-WRITTEN, not autogenerated. Autogenerate has produced destructive or
dialect-specific noise in this project twice (dd173ce633c3, bb841ad7d467), so
migrations here do exactly one thing and are covered by tests/test_schema_parity.py.

Revision ID: d81f4a2c9b03
Revises: bb841ad7d467
Create Date: 2026-08-12
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d81f4a2c9b03"
down_revision: Union[str, Sequence[str], None] = "bb841ad7d467"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "campaigns"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("niche", sa.String(), nullable=False),
        sa.Column("platform_preferences", sa.Text(), nullable=True),
        sa.Column("target_location", sa.String(), nullable=True),
        sa.Column("min_followers", sa.Integer(), nullable=True),
        sa.Column("campaign_goal", sa.String(), nullable=False),
        sa.Column("campaign_type", sa.String(), nullable=False),
        sa.Column("budget_per_creator", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("deliverables", sa.Text(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("brief", sa.Text(), nullable=True),
        sa.Column("creators_needed", sa.Integer(), nullable=True),
        sa.Column("is_open_to_applications", sa.Boolean(), nullable=False),
        # CURRENT_TIMESTAMP, not now(): portable across PostgreSQL and SQLite.
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["users.id"],
            name="campaigns_brand_id_fkey", ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="campaigns_pkey"),
    )
    op.create_index("ix_campaigns_brand_id", TABLE, ["brand_id"])
    op.create_index("ix_campaigns_brand_status", TABLE, ["brand_id", "status"])


def downgrade() -> None:
    if TABLE not in sa.inspect(op.get_bind()).get_table_names():
        return
    op.drop_index("ix_campaigns_brand_status", table_name=TABLE)
    op.drop_index("ix_campaigns_brand_id", table_name=TABLE)
    op.drop_table(TABLE)
