"""Add caching columns to CreatorProfile

Revision ID: dd173ce633c3
Revises: ede20de67a7b
Create Date: 2026-03-26 00:48:05.667525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd173ce633c3'
down_revision: Union[str, Sequence[str], None] = 'ede20de67a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    NEUTRALISED 2026-08-10 — this revision used to DROP the `saved_creators` table.

    It was generated by `alembic revision --autogenerate` at a moment when the
    SavedCreator model was not imported into Base.metadata, so autogenerate
    concluded the table was orphaned and emitted a drop — despite the revision
    being titled "Add caching columns to CreatorProfile". The actual caching
    columns are added by the NEXT revision, f9ca5e8aed1b.

    Nothing later in the chain recreated the table, so `alembic upgrade head`
    on any database that had not yet passed this point would silently destroy
    the brand-to-creator match data.

    The body is intentionally rewritten rather than reverted: this revision has
    already been applied in some environments, so it must become a no-op
    everywhere. Revision `b7e4c1a90f22` re-creates the table idempotently for
    any database that already lost it.

    Do not restore the original body.
    """
    pass


def downgrade() -> None:
    """No-op: the corresponding upgrade no longer changes anything."""
    pass
