"""Add caching columns to CreatorProfile

Revision ID: dd173ce633c3
Revises: ede20de67a7b
Create Date: 2026-03-26 00:48:05.667525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd173ce633c3'
down_revision: Union[str, Sequence[str], None] = 'ede20de67a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_creators_brand_id'), table_name='saved_creators')
    op.drop_index(op.f('ix_saved_creators_creator_id'), table_name='saved_creators')
    op.drop_table('saved_creators')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_creators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fit_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['users.id'], name=op.f('saved_creators_brand_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('saved_creators_creator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_creators_pkey'))
    )
    op.create_index(op.f('ix_saved_creators_creator_id'), 'saved_creators', ['creator_id'], unique=False)
    op.create_index(op.f('ix_saved_creators_brand_id'), 'saved_creators', ['brand_id'], unique=False)
    # ### end Alembic commands ###
