"""Add YouTube channel and video tables

Revision ID: e18862f1a8d4
Revises: 22d48585032b
Create Date: 2026-02-22 21:15:54.217094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e18862f1a8d4'
down_revision: Union[str, Sequence[str], None] = '22d48585032b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_instagram_creator_cache_username")
    op.execute("DROP TABLE IF EXISTS instagram_creator_cache")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_creator_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('instagram_creator_cache_pkey'))
    )
    op.create_index(op.f('ix_instagram_creator_cache_username'), 'instagram_creator_cache', ['username'], unique=True)
    # ### end Alembic commands ###
